"""add scheduling, surge, review replies, and notifications

Revision ID: 628d6f7c0a83
Revises: c2fb2c13e930
Create Date: 2026-08-10 05:45:26.775675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628d6f7c0a83'
down_revision: Union[str, None] = 'c2fb2c13e930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_notifications_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('scheduled_for', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('delivery_fee', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('orders', sa.Column('surge_multiplier', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('reviews', sa.Column('photo_url', sa.String(length=255), nullable=True))
    op.add_column('reviews', sa.Column('owner_reply', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('replied_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'replied_at')
    op.drop_column('reviews', 'owner_reply')
    op.drop_column('reviews', 'photo_url')
    op.drop_column('orders', 'surge_multiplier')
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'scheduled_for')
    op.drop_table('notifications')
    # ### end Alembic commands ###
