"""add driver live location

Revision ID: b1f4e5d00ff0
Revises: 628d6f7c0a83
Create Date: 2026-08-10 09:05:19.597890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f4e5d00ff0'
down_revision: Union[str, None] = '628d6f7c0a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('driver_lat', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('driver_lng', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('driver_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'driver_updated_at')
    op.drop_column('orders', 'driver_lng')
    op.drop_column('orders', 'driver_lat')
    # ### end Alembic commands ###
