"""Add payment + structured address fields to orders

Revision ID: b3e7c2a9f4d1
Revises: 38b4adc0fd48
Create Date: 2026-08-09 12:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e7c2a9f4d1'
down_revision: Union[str, None] = '38b4adc0fd48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.String(length=16), nullable=False, server_default='COD'))
    op.add_column('orders', sa.Column('payment_status', sa.String(length=16), nullable=False, server_default='PENDING'))
    op.add_column('orders', sa.Column('payment_id', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('delivery_phone', sa.String(length=15), nullable=True))
    op.add_column('orders', sa.Column('delivery_city', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('delivery_state', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('delivery_pincode', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_pincode')
    op.drop_column('orders', 'delivery_state')
    op.drop_column('orders', 'delivery_city')
    op.drop_column('orders', 'delivery_phone')
    op.drop_column('orders', 'payment_id')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
