"""Add restaurant offers scope

Revision ID: c2fb2c13e930
Revises: b3e7c2a9f4d1
Create Date: 2026-08-09 12:42:04.385670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2fb2c13e930'
down_revision: Union[str, None] = 'b3e7c2a9f4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_codes', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_promo_codes_restaurant_id', 'promo_codes', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_promo_codes_restaurant_id', 'promo_codes', type_='foreignkey')
    op.drop_column('promo_codes', 'restaurant_id')
    # ### end Alembic commands ###
