"""add restaurant city and location

Revision ID: e7d4a6f2b8c1
Revises: b1f4e5d00ff0
Create Date: 2026-08-10 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d4a6f2b8c1'
down_revision: Union[str, None] = 'b1f4e5d00ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('restaurants', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'lng')
    op.drop_column('restaurants', 'lat')
    op.drop_column('restaurants', 'city')
    # ### end Alembic commands ###
