#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "FoodAI → Render deploy"

# Values captured from the human this run. Render's URLs are public, so they
# are asked visibly and never written to .env.
BACKEND_URL=""
FRONTEND_URL=""

# _host strips scheme and trailing slash so "https://x.onrender.com/" and
# "x.onrender.com" compare equal.
_host() {
  local u="${1:-}"
  u="${u#https://}"; u="${u#http://}"; u="${u%/}"
  printf '%s' "$u"
}

# ── Stage 1: is the repo in a state Render can actually build? ─────────────
stage "Pre-flight"
say "Render builds the commit that is pushed, so local-only work is invisible."
if git rev-parse --git-dir >/dev/null 2>&1; then
  if [[ -n "$(git status --porcelain 2>/dev/null || true)" ]]; then
    warn "uncommitted changes present; Render will not see them"
  fi
  # Not `local`: these stages are top-level script code, and `local` outside a
  # function is a hard error under `set -e`.
  remote=$(git rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>/dev/null || true)
  if [[ -n "$remote" ]]; then
    remote_head=$(git rev-parse "$remote" 2>/dev/null || true)
    if [[ "$(git rev-parse HEAD)" == "$remote_head" ]]; then
      printf '  %s✓%s %s is up to date with %s\n' "$GREEN" "$RESET" "$(git rev-parse --abbrev-ref HEAD)" "$remote"
    else
      warn "HEAD differs from $remote -- push before creating the Blueprint"
    fi
  fi
else
  warn "not a git repo, skipping the sync check"
fi
note ""
note "Free tier, so expect this: Postgres data expires after 30 days, and web"
note "services sleep after ~15 idle, so the first request after a pause can"
note "hang for a minute. That is not a failure."
pause "Happy with the above?"

# ── Stage 2: create the Blueprint in GitHub ────────────────────────────────
stage "Create the Blueprint"
say "Render reads render.yaml from the repo root, so the service definitions"
say "already exist -- this stage only wires the repo to Render."
open_url "https://github.com/Veeru19252/foodai.app"
step "Open the 'New' menu at the top of the repo and choose 'Blueprint'."
step "Select this repository as the source."
step "Render reads render.yaml and shows a form for the three services:"
note "foodai-db · foodai-backend · foodai-frontend"
step "Click 'Create', then fill the two Razorpay fields (next stage)."
pause "Blueprint created?"

# ── Stage 3: the two Razorpay values ────────────────────────────────────────
stage "The two Razorpay values"
say "The form asks for RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET, marked"
say "'sync: false' in the blueprint so Render prompts instead of generating."
warn "You do not need a Razorpay account for this."
note "backend/config.py only checks these are non-empty, so any placeholder"
note "boots. Supplying real keys would not improve anything: the Razorpay"
note "checkout path is unavailable on a public deploy either way, because"
note "payments.py never calls Razorpay's Orders API. Cash on Delivery is the"
note "payment method that works."
step "Type a placeholder into both fields, e.g.: not-a-real-key"
step "Click 'Create Blueprint' and let provisioning finish."
pause "Provisioning done?"

# ── Stage 4: do the live URLs match what the blueprint hardcoded? ──────────
stage "Check the URLs against the blueprint"
say "render.yaml hardcodes the frontend origin in CORS_ORIGINS and the backend"
say "in NEXT_PUBLIC_API_URL. Both only work if Render used exactly those service"
say "names, and a mismatch fails at CORS rather than at build -- so it presents"
say "as an unexplained network error."
step "In the Render dashboard, copy each service's URL from its page."
open_url "https://dashboard.render.com/"
ask BACKEND_URL "  backend URL:  "
ask FRONTEND_URL "  frontend URL: "
note ""

BACKEND_HOST=$(_host "$BACKEND_URL")
FRONTEND_HOST=$(_host "$FRONTEND_URL")
say "blueprint expects backend:   foodai-backend.onrender.com"
say "Render gave you:            $BACKEND_HOST"
if [[ "$BACKEND_HOST" == "foodai-backend.onrender.com" ]]; then
  printf '  %s✓%s backend matches\n' "$GREEN" "$RESET"
else
  warn "backend differs -- the frontend cannot reach the API"
  note "in Render, set NEXT_PUBLIC_API_URL on foodai-frontend to:"
  note "  https://$BACKEND_HOST"
fi
note ""
say "blueprint expects frontend:  foodai-frontend.onrender.com"
say "Render gave you:            $FRONTEND_HOST"
if [[ "$FRONTEND_HOST" == "foodai-frontend.onrender.com" ]]; then
  printf '  %s✓%s frontend matches\n' "$GREEN" "$RESET"
else
  warn "frontend differs -- every API call will be blocked by CORS"
  note "in Render, set CORS_ORIGINS on foodai-backend to:"
  note "  https://$FRONTEND_HOST"
fi
note ""
note "Changing either value triggers a redeploy; wait for it to go Live."
pause "URLs sorted?"

# ── Stage 5: does the backend answer? ──────────────────────────────────────
stage "Is the backend healthy?"
say "Requesting it also wakes the service if it had gone to sleep."
step "Press Enter; the first attempt can take up to a minute."
pause ""
if command -v curl >/dev/null 2>&1 && [[ -n "$BACKEND_HOST" ]]; then
  _body=$(mktemp)
  _code=$(curl -sS -o "$_body" -w '%{http_code}' --max-time 90 \
    "https://${BACKEND_HOST}/api/health" 2>/dev/null || echo 000)
  if [[ "$_code" == "200" ]]; then
    printf '  %s✓%s /api/health returned 200\n' "$GREEN" "$RESET"
    say "  $(head -c 200 "$_body")"
  elif [[ "$_code" == "404" ]]; then
    warn "HTTP 404 -- the service is not live under that name yet"
    note "Render answers 404 for a subdomain that has no live service, so this"
    note "is the expected result if the first deploy is still building. If the"
    note "build is long finished, re-check the name against stage 4."
  elif [[ "$_code" == "503" ]]; then
    warn "HTTP 503 -- the app is up but the database is unreachable"
    note "/api/health runs a real SELECT 1, so this means DATABASE_URL is wrong"
    note "or 'alembic upgrade head' failed. The backend Logs tab has the cause."
  else
    warn "/api/health returned HTTP $_code"
    note "$(head -c 300 "$_body")"
    note "check the backend's Logs tab -- the start command runs"
    note "'alembic upgrade head' first, so schema errors surface there."
  fi
  rm -f "$_body"
else
  note "curl unavailable or no URL captured; check manually:"
  note "  https://${BACKEND_HOST:-<backend>}/api/health"
fi
pause "Backend healthy?"

# ── Stage 6: prove the flows work ──────────────────────────────────────────
stage "Smoke test"
say "Walk these in the deployed app. Anything that fails is worth fixing before"
say "you call the deploy done."
open_url "https://${FRONTEND_HOST:-<frontend>}"
step "Sign up as a customer (self-registration allows customer, restaurant and"
note "delivery -- all three work without seeding)."
step "Add an item to the cart and check out paying Cash on Delivery."
note "Razorpay is expected to be unavailable on a public deploy."
step "Watch the order's tracking timeline update while it is active."
step "Sign up as a restaurant owner and confirm the new order shows up."
step "Sign up as a driver and confirm you see only your own deliveries."
note ""
note "There is no admin on a fresh production database: seeding is off, and"
note "only an admin can promote roles. Skip admin screens, or enable"
note "SEED_DEMO_DATA with a strong DEMO_USER_PASSWORD on foodai-backend."
pause "Smoke test done?"

# ───────────────────────────────────────────────────────────────────────────

finish
note "Deploy notes are in DEPLOY.md."
note "This wizard is disposable -- delete it once the deploy is live."
